=== VanillaMaster/D/builtin/config/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "modules": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "ignore": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["path"]
        },
        "extensions": {
            "type": "object",
            "properties": {
                "ignore": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "services": {
            "type": "object",
            "properties": {
                "ignore": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cache": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                }
            },
            "required": ["path"]
        },
        "port": {
            "type": "number"
        }
    },
    "required": [
        "modules",
        "cache",
        "port"
    ]
}

=== VanillaMaster/D/config.json
{
    "$schema": "node_modules\\@builtin\\config\\schema.json",
    "cache": {
        "path": ".cache"
    },
    "modules": {
        "path": "node_modules",
        "ignore": [
            "@builtin/backend",
            "@builtin/frontend",
            "@types/*"
        ]
    },
    "extensions": {
        "ignore": []
    },
    "services": {
        "ignore": []
    },
    "port": 8080
}
